apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-incident-copilot.fullname" . }}-api
  labels:
    {{- include "ai-incident-copilot.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ai-incident-copilot.name" . }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ai-incident-copilot.name" . }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command:
            {{- toYaml .Values.api.command | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "ai-incident-copilot.fullname" . }}-config
            - secretRef:
                name: {{ include "ai-incident-copilot.fullname" . }}-secret
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
