apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-incident-copilot.fullname" . }}-secret
  labels:
    {{- include "ai-incident-copilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- /* Secret рендерится из values и обычно переопределяется на deploy. */}}
  POSTGRES_USER: {{ .Values.secret.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
