apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-incident-copilot.fullname" . }}-api
  labels:
    {{- include "ai-incident-copilot.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ai-incident-copilot.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
